const fs = require('fs');
const path = require('path');

function getPoolModule() {
    try {
        return require('pg').Pool;
    } catch (error) {
        throw new Error('The `pg` package is not installed. Run `npm install pg` to enable PostgreSQL support.');
    }
}

function normalizeTableName(tableName) {
    const candidate = (tableName || '').trim();
    if (!candidate) {
        throw new Error('Table name is required.');
    }

    if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(candidate)) {
        throw new Error(`Invalid table name: ${candidate}. Use letters, numbers, and underscore only.`);
    }

    return candidate.toLowerCase();
}

/**
 * Get default connection config from environment variables or use defaults
 */
function getDefaultConnectionConfig() {
    return {
        host: process.env.PGHOST || 'localhost',
        port: parseInt(process.env.PGPORT || '5432', 10),
        database: process.env.PGDATABASE || 'piqi',
        user: process.env.PGUSER || 'postgres',
        password: process.env.PGPASSWORD || ''
    };
}

/**
 * Create a connection pool to PostgreSQL
 * @param {Object} config - Connection configuration (host, port, database, user, password)
 * @returns {Pool} - PostgreSQL connection pool
 */
function createPool(config = {}) {
    const Pool = getPoolModule();
    const connectionConfig = { ...getDefaultConnectionConfig(), ...config };
    return new Pool(connectionConfig);
}

/**
 * Open a single client connection from pool
 * @param {Pool} pool - PostgreSQL pool
 * @returns {Promise<Client>} - Connected client
 */
async function openConnection(pool) {
    const client = await pool.connect();
    return client;
}

/**
 * Initialize PostgreSQL result store - ensures tables exist
 * @param {Pool} pool - PostgreSQL pool
 * @param {string} tableName - Evaluation run table name
 * @param {string} assessmentTableName - Assessment results table name (optional)
 */
async function initializePostgresAuditStore(pool, tableName, assessmentTableName) {
    const client = await pool.connect();
    try {
        await ensureEvaluationRunTable(client, tableName);
        if (assessmentTableName) {
            await ensureAssessmentResultsTable(client, assessmentTableName, tableName);
        }
    } finally {
        client.release();
    }
}

/**
 * Ensure the evaluation run table exists
 * @param {Client} client - PostgreSQL client
 * @param {string} tableName - Table name
 */
async function ensureEvaluationRunTable(client, tableName) {
    const safeTableName = normalizeTableName(tableName);
    
    const ddl = `
CREATE TABLE IF NOT EXISTS ${safeTableName} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_name VARCHAR(100) NOT NULL,
    piqi_model_mnemonic VARCHAR(100) NOT NULL,
    evaluation_rubric_mnemonic VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_evaluations BIGINT DEFAULT 0,
    total_records BIGINT DEFAULT 0,
    total_completed BIGINT DEFAULT 0,
    total_failed BIGINT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT ${safeTableName}_run_name_key UNIQUE (run_name)
)`;

    await client.query(ddl);

    await client.query(`
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS run_name VARCHAR(100);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS piqi_model_mnemonic VARCHAR(100);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS evaluation_rubric_mnemonic VARCHAR(100);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'IN_PROGRESS';
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS total_evaluations BIGINT DEFAULT 0;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS total_records BIGINT DEFAULT 0;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS total_completed BIGINT DEFAULT 0;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS total_failed BIGINT DEFAULT 0;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_status ON ${safeTableName}(status);
`);

    await client.query(`
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conname = '${safeTableName}_run_name_key'
          AND c.conrelid = '${safeTableName}'::regclass
    ) THEN
        ALTER TABLE ${safeTableName}
            ADD CONSTRAINT ${safeTableName}_run_name_key UNIQUE (run_name);
    END IF;
END
$$;
`);
}

/**
 * Ensure the assessment results table exists
 * @param {Client} client - PostgreSQL client
 * @param {string} tableName - Table name
 * @param {string} runTableName - Evaluation run table name
 */
async function ensureAssessmentResultsTable(client, tableName, runTableName = 'piqi_evaluation_run') {
    const safeTableName = normalizeTableName(tableName);
    const safeRunTableName = normalizeTableName(runTableName);
    
    const ddl = `
CREATE TABLE IF NOT EXISTS ${safeTableName} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    row_num INTEGER,
    message_id TEXT NOT NULL,
    data_class VARCHAR(50) NOT NULL,
    attribute_name TEXT NOT NULL,
    attribute_value TEXT,
    assessment VARCHAR(50),
    status VARCHAR(50),
    reason TEXT,
    effect TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_${safeTableName}_run_id FOREIGN KEY (run_id)
        REFERENCES ${safeRunTableName}(id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)`;

    await client.query(ddl);

    await client.query(`
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS run_id BIGINT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS row_num INTEGER;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS message_id TEXT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS data_class VARCHAR(50);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS attribute_name TEXT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS attribute_value TEXT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS assessment VARCHAR(50);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS status VARCHAR(50);
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS reason TEXT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS effect TEXT;
ALTER TABLE ${safeTableName} ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_run_id ON ${safeTableName}(run_id);
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_message_id ON ${safeTableName}(message_id);
CREATE INDEX IF NOT EXISTS idx_${safeTableName}_run_message ON ${safeTableName}(run_id, message_id);
`);

    await client.query(`
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_attribute a
          ON a.attrelid = c.conrelid
         AND a.attnum = ANY (c.conkey)
        WHERE c.contype = 'f'
          AND c.conrelid = '${safeTableName}'::regclass
          AND c.confrelid = '${safeRunTableName}'::regclass
          AND a.attname = 'run_id'
    ) THEN
        ALTER TABLE ${safeTableName}
            ADD CONSTRAINT fk_${safeTableName}_run_id
            FOREIGN KEY (run_id)
            REFERENCES ${safeRunTableName}(id)
            ON UPDATE NO ACTION
            ON DELETE CASCADE;
    END IF;
END
$$;
`);
}

/**
 * Create a new evaluation run row and return its numeric id.
 * @param {Client} client - PostgreSQL client
 * @param {Object} options - Run creation options
 * @param {string} options.runName - Unique run name
 * @param {string} options.piqiModelMnemonic - PIQI model mnemonic
 * @param {string} options.evaluationRubricMnemonic - Evaluation rubric mnemonic
 * @param {number} options.totalRecords - Total records expected in this run
 * @returns {Promise<number>} - Evaluation run id
 */
async function createEvaluationRun(client, tableName, options) {
    const safeTableName = normalizeTableName(tableName);
    const totalRecords = options.totalRecords || 0;

    const sql = `
INSERT INTO ${safeTableName} (
    run_name,
    piqi_model_mnemonic,
    evaluation_rubric_mnemonic,
    status,
    total_evaluations,
    total_records,
    total_completed,
    total_failed
) VALUES ($1, $2, $3, 'IN_PROGRESS', $4, $5, 0, 0)
RETURNING id`;

    const result = await client.query(sql, [
        options.runName,
        options.piqiModelMnemonic,
        options.evaluationRubricMnemonic,
        totalRecords,
        totalRecords
    ]);
    return result.rows[0].id;
}

/**
 * Increment run completion/failure counters as rows are processed.
 * @param {Client} client - PostgreSQL client
 * @param {string} tableName - Evaluation run table name
 * @param {number} runId - Evaluation run id
 * @param {number} completedIncrement - Increment for completed count
 * @param {number} failedIncrement - Increment for failed count
 */
async function incrementEvaluationRunCounts(client, tableName, runId, completedIncrement, failedIncrement) {
    const safeTableName = normalizeTableName(tableName);

    const sql = `
UPDATE ${safeTableName}
SET
    total_completed = COALESCE(total_completed, 0) + $2,
    total_failed = COALESCE(total_failed, 0) + $3
WHERE id = $1`;

    await client.query(sql, [runId, completedIncrement, failedIncrement]);
}

/**
 * Finalize an evaluation run with terminal status and completion timestamp.
 * @param {Client} client - PostgreSQL client
 * @param {string} tableName - Evaluation run table name
 * @param {number} runId - Evaluation run id
 * @param {string} status - Terminal status
 */
async function finalizeEvaluationRun(client, tableName, runId, status = 'COMPLETED') {
    const safeTableName = normalizeTableName(tableName);

    const sql = `
UPDATE ${safeTableName}
SET
    status = $2,
    completed_at = NOW()
WHERE id = $1`;

    await client.query(sql, [runId, status]);
}

/**
 * Insert assessment results
 * @param {Client} client - PostgreSQL client
 * @param {string} tableName - Table name
 * @param {Array} assessmentRecords - Array of assessment records
 */
async function insertAssessmentResults(client, tableName, assessmentRecords) {
    if (!assessmentRecords || assessmentRecords.length === 0) {
        return;
    }

    const safeTableName = normalizeTableName(tableName);

    if (assessmentRecords.some((record) => record.runId === undefined || record.runId === null)) {
        throw new Error('PostgreSQL assessment records must include runId for all rows.');
    }

    if (assessmentRecords.some((record) => record.rowNum === undefined || record.rowNum === null)) {
        throw new Error('PostgreSQL assessment records must include rowNum for all rows.');
    }

    const sql = `
INSERT INTO ${safeTableName} (
    run_id,
    row_num,
    message_id,
    data_class,
    attribute_name,
    attribute_value,
    assessment,
    status,
    reason,
    effect
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)`;

    for (const record of assessmentRecords) {
        const values = [
            record.runId,
            record.rowNum,
            record.messageId,
            record.dataClass,
            record.attributeName,
            record.attributeValue,
            record.assessment,
            record.status,
            record.reason,
            record.effect
        ];
        await client.query(sql, values);
    }
}

/**
 * Run the schema.sql file to initialize all tables
 * @param {Pool} pool - PostgreSQL pool
 */
async function runSchemaFile(pool) {
    const schemaPath = path.join(__dirname, 'schema.sql');
    const schemaSql = fs.readFileSync(schemaPath, 'utf8');
    
    const client = await pool.connect();
    try {
        await client.query(schemaSql);
    } finally {
        client.release();
    }
}

module.exports = {
    createPool,
    openConnection,
    initializePostgresAuditStore,
    ensureEvaluationRunTable,
    ensureAssessmentResultsTable,
    createEvaluationRun,
    incrementEvaluationRunCounts,
    finalizeEvaluationRun,
    insertAssessmentResults,
    normalizeTableName,
    getDefaultConnectionConfig,
    runSchemaFile
};
