-- PostgreSQL schema for PIQI Tools
-- Verify-first and additive updates for evaluation run + assessment results.

CREATE TABLE IF NOT EXISTS public.piqi_evaluation_run
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    run_name character varying(100) NOT NULL,
    piqi_model_mnemonic character varying(100) NOT NULL,
    evaluation_rubric_mnemonic character varying(100) NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'IN_PROGRESS',
    total_evaluations bigint DEFAULT 0,
    total_records bigint DEFAULT 0,
    total_completed bigint DEFAULT 0,
    total_failed bigint DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    completed_at timestamp with time zone,
    CONSTRAINT pk_piqi_evaluation_run PRIMARY KEY (id),
    CONSTRAINT piqi_evaluation_run_run_name_key UNIQUE (run_name)
);

CREATE TABLE IF NOT EXISTS public.piqi_evaluation_results
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    run_id bigint NOT NULL,
    row_num integer,
    message_id text NOT NULL,
    data_class character varying(50) NOT NULL,
    attribute_name text NOT NULL,
    attribute_value text,
    assessment character varying(50),
    status character varying(50),
    reason text,
    effect text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT pk_piqi_evaluation_results PRIMARY KEY (id),
    CONSTRAINT fk_results_to_run FOREIGN KEY (run_id)
        REFERENCES public.piqi_evaluation_run (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- Additive alignment for existing installations where tables already exist.
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS run_name character varying(100);
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS piqi_model_mnemonic character varying(100);
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS evaluation_rubric_mnemonic character varying(100);
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS status character varying(20) DEFAULT 'IN_PROGRESS';
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS total_evaluations bigint DEFAULT 0;
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS total_records bigint DEFAULT 0;
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS total_completed bigint DEFAULT 0;
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS total_failed bigint DEFAULT 0;
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.piqi_evaluation_run ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;

ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS run_id bigint;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS row_num integer;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS message_id text;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS data_class character varying(50);
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS attribute_name text;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS attribute_value text;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS assessment character varying(50);
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS status character varying(50);
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS effect text;
ALTER TABLE public.piqi_evaluation_results ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        WHERE c.conname = 'piqi_evaluation_run_run_name_key'
          AND c.conrelid = 'public.piqi_evaluation_run'::regclass
    ) THEN
        ALTER TABLE public.piqi_evaluation_run
            ADD CONSTRAINT piqi_evaluation_run_run_name_key UNIQUE (run_name);
    END IF;
END
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint c
        JOIN pg_attribute a
          ON a.attrelid = c.conrelid
         AND a.attnum = ANY (c.conkey)
        WHERE c.contype = 'f'
        AND c.conrelid = 'public.piqi_evaluation_results'::regclass
          AND c.confrelid = 'public.piqi_evaluation_run'::regclass
          AND a.attname = 'run_id'
    ) THEN
        ALTER TABLE public.piqi_evaluation_results
            ADD CONSTRAINT fk_results_to_run
            FOREIGN KEY (run_id)
            REFERENCES public.piqi_evaluation_run (id)
            ON UPDATE NO ACTION
            ON DELETE CASCADE;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_piqi_evaluation_run_status
    ON public.piqi_evaluation_run (status);

CREATE INDEX IF NOT EXISTS idx_piqi_evaluation_results_run_id
    ON public.piqi_evaluation_results (run_id);

CREATE INDEX IF NOT EXISTS idx_piqi_evaluation_results_message_id
    ON public.piqi_evaluation_results (message_id);

CREATE INDEX IF NOT EXISTS idx_piqi_evaluation_results_run_message
    ON public.piqi_evaluation_results (run_id, message_id);
