# Point to your existing Postgres service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/fhir?currentSchema=hapi
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FHIR Version
hapi.fhir.fhir_version=R4

# Terminology Configuration
hapi.fhir.terminology_server_enabled=true
hapi.fhir.allow_external_references=false

# Logging
logging.level.org.hibernate.cfg.Environment=DEBUG