# Database configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_CONN_STRING}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Duck DB Properties
duckdb.file=

# PIQI Server configuration
piqi.api.base-url=http://localhost/piqi
piqi.score-path=/PIQI/ScoreAuditMessage
piqi.timeout-ms=30000

# Logging Properties
logging.level.root=WARN
logging.level.dev.ikm.dq=DEBUG
logging.file.name=logs/cli.log
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n