dotenv.path=../.env

# Root level
logging.level.root=WARN

# Your app package only
logging.level.dev.ikm.dq=DEBUG

# Optional: log to file
logging.file.name=logs/cli.log
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg%n

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_CONN_STRING}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.chaangelog-master.yaml